#!/bin/bash
# Regenerates shaders_spv.h from the GLSL sources. Needs glslangValidator.
set -e
cd "$(dirname "$0")"
out=shaders_spv.h
echo "// Generated by compile.sh from fullscreen.vert and ycbcr_to_rgb.frag. Do not edit." > $out
echo "#pragma once" >> $out
echo "#include <cstdint>" >> $out
for src in fullscreen.vert ycbcr_to_rgb.frag; do
    name=$(echo "$src" | tr '.' '_')
    glslangValidator -V --target-env vulkan1.3 -Os --vn "k_${name}" -o "/tmp/pw_${name}.h" "$src" > /dev/null
    sed -e 's/^const uint32_t/static const uint32_t/' "/tmp/pw_${name}.h" | grep -v 'pragma once' | grep -v '^\s*//' >> $out
    rm "/tmp/pw_${name}.h"
done
